name: Auto-add to Life Project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    if: github.actor == 'TechnicallyShaun'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@158aad9ed186a4842abf69d0f8071a0ff95312d0 # v1.0.2+
        with:
          project-url: https://github.com/users/TechnicallyShaun/projects/5
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
